doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        driver: 'pdo_mysql'
        server_version: '5.7'
        charset: utf8
        default_table_options:
            charset: utf8
            collate: utf8_general_ci
        types:
            PlayId: TicTacToe\Play\Infrastructure\Domain\Doctrine\Aggregate\DoctrinePlayId
    orm:
        auto_generate_proxy_classes: true
#        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
#        auto_mapping: true
        entity_managers:
            default:
                mappings:
                    Play:
                        is_bundle: false
                        type: xml
                        dir: "%kernel.project_dir%/src/TicTacToe/Play/Infrastructure/Domain/Doctrine/Persistence/Mapping"
                        prefix: 'TicTacToe\Play\Domain'

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
