services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  TicTacToe\Play\Infrastructure\Communication\Http\Symfony\Controller\:
    resource: '%kernel.project_dir%/src/TicTacToe/Play/Infrastructure/Communication/Http/Symfony/Controller'
    tags: ['controller.service_arguments']