services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  TicTacToe\Play\Application\DataTransformer\:
    resource: '%kernel.project_dir%/src/TicTacToe/Play/Application/DataTransformer/*'
